baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'API Neuchâtel'
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fr]
    title = "API Neuchâtel Fr"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  mainSections = ["evenements"]
  description = "L’association des professionnels de l’informatique (API) soutient le secteur informatique dans le canton de Neuchâtel et au-delà"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/API_Neuchatel"
